### ISSUE TITLE
Seems to not handle some users correctly

### ISSUE THREAD

**Issue by MarcosBL** [rtfeldman/elm-spa-example#11] opened 2017-05-10 07:47 UTC
As per demo: http://rtfeldman.github.io/elm-spa-example/#/profile/skuld.am

**Comment by rtfeldman** [comment] 2018-02-01 03:17
Duplicate of https://github.com/rtfeldman/elm-spa-example/issues/38

**Closed by rtfeldman** 2018-02-01 03:17 UTC
